spring:
  cache:
    type: redis

  application:
    name: Mania-Place

  datasource:
    url: jdbc:mysql://localhost:3306/mania_place
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate.ddl-auto: create
#    hibernate.ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true


jwt:
  secret:
    key: ${SECRET_KEY}
