spring:
  cache:
    type: redis

  application:
    name: Mania-Place

  datasource:
    url: jdbc:mysql://localhost:3307/mania_place
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    #    hibernate.ddl-auto: create
    hibernate.ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true

jwt:
  secret:
    key: 7b4b2adee30710c60625c93a6bbc433e456e3d8e2a5489d655249d5262c7a1fec010662cfee5073ca66c6658a9fc823805240958bec415b9cdf27103dde5fa39
