spring:
  cache:
    type: redis

  application:
    name: Plus-Project

  datasource:
    url: jdbc:mysql://localhost:3306/
    driver-class-name: com.mysql.cj.jdbc.Driver
    username:
    password:

  jpa:
    hibernate.ddl-auto: create-drop
#    hibernate.ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true

#  data:
#    redis:
#      host: 127.0.0.1
#      port: 6379

jwt:
  secret:
    key:
    # (필요하다면) 파일 경로 환경 변수로 추가 필요
