---
name: feature
about: 새로운 기능 개발을 위한 템플릿
title: '[FEATURE] '
labels: feature
assignees: ''
---

## ✨ 기능 설명
개발할 기능에 대해 간단히 설명해주세요.

## 📋 요구사항
- [ ] 요구사항 1
- [ ] 요구사항 2
- [ ] 요구사항 3

## 🎯 완료 조건 (Acceptance Criteria)
- [ ] 조건 1
- [ ] 조건 2
- [ ] 조건 3

## 🔗 관련 이슈
- 관련 이슈: #
- 의존하는 이슈: #

## 📝 추가 정보
필요한 경우 추가 정보나 참고 자료를 첨부해주세요.
