name: 🛠 작업 시작: 새로운 기능 구현
description: 내가 만들 기능을 공유하고 작업을 시작합니다
title: "[FEATURE] "
labels: ["feature", "in progress"]
body:
  - type: markdown
    attributes:
      value: |
        👋 구현하고자 하는 기능과 간단한 계획을 공유해주세요!

  - type: input
    id: summary
    attributes:
      label: 기능 제목
      placeholder: 예) 게시글 좋아요 기능

  - type: textarea
    id: what
    attributes:
      label: 어떤 기능인가요?
      description: 개발할 기능을 간단히 설명해주세요
      placeholder: 예) 사용자가 게시글에 좋아요를 누를 수 있는 기능입니다
    validations:
      required: true

  - type: textarea
    id: plan
    attributes:
      label: 어떻게 구현할 예정인가요?
      description: 주요 구현 단계나 기술 스택 등을 작성해주세요
      placeholder: |
        - 게시글 테이블에 like_count 필드 추가
        - 좋아요 POST API 구현
        - 클라이언트에서 UI 버튼 연결
    validations:
      required: false

  - type: textarea
    id: discussion
    attributes:
      label: 논의할 점이 있다면 적어주세요
      description: 구현 전에 팀원들과 이야기해보고 싶은 점이 있다면 여기에 작성해주세요
      placeholder: 예) 좋아요 취소 기능도 같이 넣을까요?
    validations:
      required: false

