name: feature
description: 새로운 기능 개발을 위한 템플릿
title: '[FEATURE] '
labels: ['feature']
assignees: []
body:
  - type: textarea
    id: feature-description
    attributes:
      label: 기능 설명
      description: 개발할 기능에 대해 간단히 설명해주세요.
      placeholder: 어떤 기능을 개발하시나요?
    validations:
      required: true
  
  - type: checkboxes
    id: requirements
    attributes:
      label: 요구사항
      description: 기능 개발을 위한 요구사항을 체크해주세요.
      options:
        - label: 요구사항 1
        - label: 요구사항 2
        - label: 요구사항 3
  
  - type: textarea
    id: related-issues
    attributes:
      label: 관련 이슈
      description: 관련된 이슈나 의존하는 이슈가 있다면 링크해주세요.
      placeholder: |
        - 관련 이슈: #
        - 의존하는 이슈: #
  
  - type: textarea
    id: additional-info
    attributes:
      label: 추가 정보
      description: 필요한 경우 추가 정보나 참고 자료를 첨부해주세요.
      placeholder: 스크린샷, 와이어프레임, 참고 링크 등
