name: Issue Branch Automation

on:
  issues:
    types: [opened]
  pull_request:
    types: [closed]

jobs:
  create-branch:
    if: github.event_name == 'issues' && github.event.action == 'opened'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Extract branch prefix from labels
        id: extract-prefix
        run: |
          LABELS=$(echo '${{ toJson(github.event.issue.labels) }}' | jq -r '.[].name')
          PREFIX="feat"  # 기본값

          for label in $LABELS; do
            case "$label" in
              "bug"|"fix") PREFIX="fix" ;;
              "feature"|"enhancement") PREFIX="feat" ;;
              "refactor"|"refactoring") PREFIX="refactor" ;;
              "chore"|"maintenance") PREFIX="chore" ;;
              "docs"|"documentation") PREFIX="docs" ;;
              "hotfix") PREFIX="hotfix" ;;
              "test"|"testing") PREFIX="test" ;;
            esac
          done

          echo "prefix=$PREFIX" >> $GITHUB_OUTPUT

      - name: Sanitize title and create branch name
        id: create-branch-name
        run: |
          ISSUE_NUMBER=${{ github.event.issue.number }}
          PREFIX=${{ steps.extract-prefix.outputs.prefix }}
          ISSUE_TITLE="${{ github.event.issue.title }}"

          echo "Debug - Original title: '$ISSUE_TITLE'"
          echo "Debug - Issue number: '$ISSUE_NUMBER'"
          echo "Debug - Prefix: '$PREFIX'"

          # 제목이 비어있거나 공백만 있는 경우 체크
          if [[ -z "$ISSUE_TITLE" || "$ISSUE_TITLE" =~ ^[[:space:]]*$ ]]; then
            echo "Warning: Issue title is empty or contains only whitespace"
            SANITIZED_TITLE="issue"
          else
            # 제목 정리 단계별 처리
            # 1. 먼저 **를 제거하고 공백 정리
            TEMP_TITLE=$(echo "$ISSUE_TITLE" | sed 's/\*\*//g' | sed 's/^ *//g' | sed 's/ *$//g')
            echo "Debug - After removing **: '$TEMP_TITLE'"
            
            # 2. 소문자 변환
            TEMP_TITLE=$(echo "$TEMP_TITLE" | tr '[:upper:]' '[:lower:]')
            echo "Debug - After lowercase: '$TEMP_TITLE'"
            
            # 3. 허용되지 않는 문자를 하이픈으로 변경 (영문, 숫자, 한글, 하이픈, 언더스코어만 허용)
            TEMP_TITLE=$(echo "$TEMP_TITLE" | sed 's/[^a-z0-9가-힣ㄱ-ㅎㅏ-ㅣ_-]/-/g')
            echo "Debug - After char replacement: '$TEMP_TITLE'"
            
            # 4. 연속된 하이픈을 하나로 줄이기
            TEMP_TITLE=$(echo "$TEMP_TITLE" | sed 's/-\+/-/g')
            echo "Debug - After dash reduction: '$TEMP_TITLE'"
            
            # 5. 앞뒤 하이픈 제거
            TEMP_TITLE=$(echo "$TEMP_TITLE" | sed 's/^-\+//' | sed 's/-\+$//')
            echo "Debug - After trim dashes: '$TEMP_TITLE'"
            
            # 6. 길이 제한 (50자)
            if [[ ${#TEMP_TITLE} -gt 50 ]]; then
              TEMP_TITLE="${TEMP_TITLE:0:50}"
              # 끝에 하이픈이 있으면 제거
              TEMP_TITLE=$(echo "$TEMP_TITLE" | sed 's/-\+$//')
            fi
            
            # 7. 여전히 비어있으면 기본값 설정
            if [[ -z "$TEMP_TITLE" || "$TEMP_TITLE" == "-" ]]; then
              SANITIZED_TITLE="issue"
            else
              SANITIZED_TITLE="$TEMP_TITLE"
            fi
          fi

          BRANCH_NAME="${PREFIX}/${ISSUE_NUMBER}-${SANITIZED_TITLE}"

          echo "Debug - Sanitized title: '$SANITIZED_TITLE'"
          echo "Debug - Final branch name: '$BRANCH_NAME'"

          echo "branch_name=$BRANCH_NAME" >> $GITHUB_OUTPUT
          echo "sanitized_title=$SANITIZED_TITLE" >> $GITHUB_OUTPUT

      - name: Debug branch values
        run: |
          echo "=== Debug Information ==="
          echo "Original title: '${{ github.event.issue.title }}'"
          echo "Sanitized title: '${{ steps.create-branch-name.outputs.sanitized_title }}'"
          echo "Branch name: '${{ steps.create-branch-name.outputs.branch_name }}'"
          echo "Issue number: '${{ github.event.issue.number }}'"
          echo "Prefix: '${{ steps.extract-prefix.outputs.prefix }}'"
          echo "========================"

      - name: Create and push branch
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -e  # 에러 발생 시 즉시 종료
          
          echo "=== Branch Creation Process ==="
          echo "Branch name: '${{ steps.create-branch-name.outputs.branch_name }}'"
          
          # Git 설정
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          
          # 브랜치명 유효성 검사
          BRANCH_NAME="${{ steps.create-branch-name.outputs.branch_name }}"
          if [[ -z "$BRANCH_NAME" ]]; then
            echo "ERROR: Branch name is empty!"
            exit 1
          fi
          
          echo "Fetching origin..."
          git fetch origin
          
          # 베이스 브랜치 확인
          if git show-ref --verify --quiet refs/remotes/origin/develop; then
            BASE_BRANCH="develop"
          elif git show-ref --verify --quiet refs/remotes/origin/main; then
            BASE_BRANCH="main"
          else
            echo "ERROR: Neither develop nor main branch found!"
            git branch -r
            exit 1
          fi
          
          echo "Base branch: $BASE_BRANCH"
          
          # 브랜치가 이미 존재하는지 확인
          if git show-ref --verify --quiet refs/remotes/origin/"$BRANCH_NAME"; then
            echo "WARNING: Branch $BRANCH_NAME already exists!"
            exit 0
          fi
          
          # 브랜치 생성
          echo "Creating branch: $BRANCH_NAME"
          git checkout -b "$BRANCH_NAME" origin/$BASE_BRANCH
          
          if [[ $? -ne 0 ]]; then
            echo "ERROR: Failed to create branch!"
            exit 1
          fi
          
          # 브랜치 푸시
          echo "Pushing branch: $BRANCH_NAME"
          git push origin "$BRANCH_NAME"
          
          if [[ $? -ne 0 ]]; then
            echo "ERROR: Failed to push branch!"
            exit 1
          fi
          
          echo "SUCCESS: Branch created and pushed successfully!"

      - name: Add branch info to issue
        if: success()
        uses: peter-evans/create-or-update-comment@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          body: |
            🚀 **브랜치가 자동 생성되었습니다!**

            **브랜치명**: `${{ steps.create-branch-name.outputs.branch_name }}`

            ### 다음 단계
            1. 로컬에서 브랜치 체크아웃:
               ```bash
               git fetch origin
               git checkout ${{ steps.create-branch-name.outputs.branch_name }}
               ```
            2. 작업 완료 후 PR 생성
            3. PR이 머지되면 브랜치와 이슈가 자동으로 정리됩니다

            > 💡 **팁**: PR 제목에 `closes #${{ github.event.issue.number }}` 또는 `fixes #${{ github.event.issue.number }}`를 포함하면 이슈가 자동으로 닫힙니다.

      - name: Add error info to issue
        if: failure()
        uses: peter-evans/create-or-update-comment@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          body: |
            ❌ **브랜치 생성 실패!**

            **오류**: 브랜치 생성 중 문제가 발생했습니다.
            **예상 브랜치명**: `${{ steps.create-branch-name.outputs.branch_name }}`

            ### 확인사항
            - 브랜치명에 특수문자가 포함되어 있는지 확인
            - 동일한 브랜치가 이미 존재하는지 확인
            - GitHub Actions 로그를 확인하여 자세한 오류 내용 확인

            수동으로 브랜치를 생성하거나 이슈 제목을 수정 후 새 이슈를 생성해주세요.

      - name: Add labels to issue
        uses: peter-evans/create-or-update-comment@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          body: |
            ---
            🏷️ **브랜치 정보**
            - **타입**: `${{ steps.extract-prefix.outputs.prefix }}`
            - **브랜치**: `${{ steps.create-branch-name.outputs.branch_name }}`
            - **상태**: 🔄 진행 중

  cleanup-after-merge:
    if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Extract issue number from branch name
        id: extract-issue
        run: |
          BRANCH_NAME="${{ github.event.pull_request.head.ref }}"
          echo "branch_name=$BRANCH_NAME" >> $GITHUB_OUTPUT

          ISSUE_NUMBER=$(echo "$BRANCH_NAME" | grep -oE '/[0-9]+' | sed 's/\///')

          if [[ "$ISSUE_NUMBER" =~ ^[0-9]+$ ]]; then
            echo "issue_number=$ISSUE_NUMBER" >> $GITHUB_OUTPUT
            echo "has_issue=true" >> $GITHUB_OUTPUT
          else
            echo "has_issue=false" >> $GITHUB_OUTPUT
          fi

      - name: Delete merged branch
        if: steps.extract-issue.outputs.has_issue == 'true'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          BRANCH_NAME="${{ steps.extract-issue.outputs.branch_name }}"
          git push origin --delete "$BRANCH_NAME" || echo "브랜치 삭제 실패 또는 이미 삭제됨"

      - name: Close related issue
        if: steps.extract-issue.outputs.has_issue == 'true'
        uses: peter-evans/create-or-update-comment@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ steps.extract-issue.outputs.issue_number }}
          body: |
            ✅ **작업이 완료되었습니다!**

            **PR**: #${{ github.event.pull_request.number }} - ${{ github.event.pull_request.title }}
            **브랜치**: `${{ steps.extract-issue.outputs.branch_name }}` (삭제됨)
            **머지 시간**: ${{ github.event.pull_request.merged_at }}

            이 이슈는 자동으로 닫힙니다. 🎉

      - name: Close issue
        if: steps.extract-issue.outputs.has_issue == 'true'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ISSUE_NUMBER=${{ steps.extract-issue.outputs.issue_number }}
          gh issue close $ISSUE_NUMBER --reason completed
